import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "./_component/Navbar/Navbar";
import Footer from "./_component/Footer/Footer";
import FirstNav from "./_component/FirstNav/FirstNav";
import LastNav from "./_component/LastNav/LastNav";

import { Weight } from "lucide-react";
import { Toaster } from "@/components/ui/toast";
import { SessionProvider } from "next-auth/react";
import MyProvider from "./_component/MyProvider/MyProvider";
import Providers from "./_component/TanstackProvider/TanstackProvider";
import ReduxProvider from "./ReduxProvider/ReduxProvider";

const Exofont = Exo({
  variable: "--font-Exo",
  weight: ["100", "400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${Exofont.className} antialiased`}
      suppressHydrationWarning
    >
      <body className="">
        <Providers>
          <ReduxProvider>
            <MyProvider>
              <FirstNav />
              <Navbar />

              <div className="container mx-auto xl:max-w-7xl">
                {children}
                <Toaster />
              </div>
              <LastNav />
              <Footer />
            </MyProvider>
          </ReduxProvider>
        </Providers>
      </body>
    </html>
  );
}
